# Generated by Django 5.1.3 on 2024-12-18 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='chat_session_start_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 18, 15, 24, 40, 380000, tzinfo=datetime.timezone.utc)),
        ),
    ]
