# Generated by Django 5.1.3 on 2024-12-18 15:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chathistory_chat_session_start_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='has_interaction',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='chat_session_start_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='response_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
