# Generated by Django 5.1.3 on 2024-12-15 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserManager',
            new_name='UserAccountManager',
        ),
    ]
